name: dart_parsing
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

flutter:
  assets:
    - assets/

dependencies:
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
